#!/usr/bin/env python3
"""
Surgical Scout - Main script
Reads case list, searches PubMed, extracts clinical pearls, and emails digest
"""

import os
import sys
import logging
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

import engine
import email_sender
import pdf_downloader
import pdf_processor
import browser_session

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler('surgical_scout.log')
    ]
)
logger = logging.getLogger(__name__)


def load_cases(cases_file: str = "cases.txt") -> list:
    """
    Load surgical cases from text file

    Args:
        cases_file: Path to cases file

    Returns:
        List of procedure names
    """
    try:
        cases_path = Path(cases_file)

        if not cases_path.exists():
            logger.error(f"Cases file not found: {cases_file}")
            return []

        with open(cases_path, 'r') as f:
            lines = f.readlines()

        # Filter out empty lines and comments
        cases = []
        for line in lines:
            line = line.strip()
            if line and not line.startswith('#'):
                cases.append(line)

        logger.info(f"Loaded {len(cases)} cases from {cases_file}")
        return cases

    except Exception as e:
        logger.error(f"Error loading cases file: {e}")
        return []


def create_html_email(digest_data: dict) -> str:
    """
    Create HTML email from digest data

    Args:
        digest_data: Dictionary with procedure names as keys and HTML content as values

    Returns:
        Complete HTML email body
    """
    today = datetime.now().strftime("%B %d, %Y")

    html = f"""
    <html>
    <head>
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f5f5f5;
            }}
            .container {{
                background-color: white;
                padding: 30px;
                border-radius: 8px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }}
            .header {{
                border-bottom: 3px solid #2c3e50;
                padding-bottom: 20px;
                margin-bottom: 30px;
            }}
            h1 {{
                color: #2c3e50;
                margin: 0;
                font-size: 28px;
            }}
            .date {{
                color: #7f8c8d;
                font-size: 14px;
                margin-top: 5px;
            }}
            h2 {{
                color: #34495e;
                border-left: 4px solid #3498db;
                padding-left: 15px;
                margin-top: 40px;
                margin-bottom: 20px;
                font-size: 22px;
            }}
            h3 {{
                color: #2c3e50;
                font-size: 18px;
                margin-top: 25px;
                margin-bottom: 10px;
            }}
            p {{
                margin: 10px 0;
            }}
            strong {{
                color: #2c3e50;
            }}
            a {{
                color: #3498db;
                text-decoration: none;
            }}
            a:hover {{
                text-decoration: underline;
            }}
            hr {{
                border: none;
                border-top: 1px solid #ecf0f1;
                margin: 25px 0;
            }}
            .footer {{
                margin-top: 40px;
                padding-top: 20px;
                border-top: 2px solid #ecf0f1;
                text-align: center;
                color: #7f8c8d;
                font-size: 14px;
            }}
            .no-results {{
                color: #7f8c8d;
                font-style: italic;
                padding: 15px;
                background-color: #f8f9fa;
                border-radius: 4px;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🔍 Your Surgical Literature Update</h1>
                <div class="date">{today}</div>
            </div>
    """

    # Add content for each procedure
    for procedure, content in digest_data.items():
        html += f"\n            <h2>{procedure}</h2>\n"
        html += f"            {content}\n"

    # Add footer
    html += """
            <div class="footer">
                <p>Generated by <strong>Surgical Scout</strong></p>
                <p>Powered by PubMed & Claude AI</p>
            </div>
        </div>
    </body>
    </html>
    """

    return html


def main():
    """Main execution function"""
    print("=" * 60)
    print("SURGICAL SCOUT - Literature Digest System")
    print("=" * 60)
    print()

    # Load environment variables (override any existing ones)
    load_dotenv(override=True)

    # Verify required environment variables
    required_vars = [
        "PUBMED_EMAIL",
        "SENDER_EMAIL",
        "SENDER_PASSWORD",
        "RECIPIENT_EMAIL",
        "GOOGLE_API_KEY"
    ]

    missing_vars = [var for var in required_vars if not os.getenv(var)]
    if missing_vars:
        logger.error(f"Missing required environment variables: {', '.join(missing_vars)}")
        print(f"\n❌ ERROR: Missing configuration in .env file:")
        for var in missing_vars:
            print(f"   - {var}")
        print("\nPlease update your .env file and try again.")
        sys.exit(1)

    # Load cases
    cases = load_cases("cases.txt")

    if not cases:
        logger.error("No cases found to process")
        print("\n❌ ERROR: No cases found in cases.txt")
        print("Please add procedures to cases.txt (one per line) and try again.")
        sys.exit(1)

    print(f"📋 Found {len(cases)} procedures to scout:")
    for case in cases:
        print(f"   • {case}")
    print()

    # Get email for API requests
    email = os.getenv("PUBMED_EMAIL")

    # Browser session disabled for now (ChromeDriver compatibility issues)
    # Using free sources (PMC + Unpaywall) which work reliably
    print("📚 Using free sources for full-text access (PMC + Unpaywall)...")
    auth_session = None
    use_browser = False
    print()

    # Process each case
    digest_data = {}
    successful_cases = 0
    full_text_count = 0
    abstract_count = 0
    source_stats = {"PMC": 0, "Unpaywall": 0, "Browser": 0}

    for i, procedure in enumerate(cases, 1):
        print(f"[{i}/{len(cases)}] Scouting: {procedure}...")

        try:
            # Search PubMed
            print(f"    └─ Searching PubMed...")
            articles = engine.search_pubmed(procedure)

            if not articles:
                print(f"    └─ No articles found")
                digest_data[procedure] = "<p class='no-results'>No recent articles found in target journals.</p>"
                print()
                continue

            print(f"    └─ Found {len(articles)} articles")

            # Try to get full-text PDFs from multiple sources
            pdf_contents = []
            if use_browser:
                print(f"    └─ Checking for full-text access (PMC/Unpaywall/Browser)...")
            else:
                print(f"    └─ Checking for free full-text access (PMC/Unpaywall)...")

            downloader = pdf_downloader.PDFDownloader(session=auth_session)

            for j, article in enumerate(articles[:3], 1):  # Limit to 3 articles for cost
                try:
                    # Try to get full-text URL
                    result = engine.try_get_full_text(article, email, use_browser=use_browser)

                    if result:
                        pdf_url, source = result
                        print(f"        └─ Found {source} PDF for article {j}/3")
                        source_stats[source] = source_stats.get(source, 0) + 1

                        # Download PDF
                        pdf_path = downloader.download_from_url(
                            pdf_url,
                            article['pmid'],
                            procedure
                        )

                        if pdf_path:
                            print(f"        └─ Downloaded article {j}/3")
                            # Extract content from PDF
                            content = pdf_processor.extract_pdf_content(str(pdf_path))
                            pdf_contents.append(content)
                        else:
                            print(f"        └─ Download failed for article {j}/3")
                    else:
                        print(f"        └─ No full-text PDF for article {j}/3")

                except Exception as e:
                    logger.warning(f"Could not process article {j}: {e}")
                    continue

            # Analyze content
            if pdf_contents:
                print(f"    └─ Analyzing {len(pdf_contents)} full articles with Gemini...")
                analysis_html = engine.analyze_full_text_articles(pdf_contents, procedure)
                digest_data[procedure] = analysis_html
                successful_cases += 1
                full_text_count += len(pdf_contents)
                print(f"    └─ ✓ Complete ({len(pdf_contents)} full-text)")
            else:
                # Fallback to abstract analysis
                print(f"    └─ Analyzing abstracts with Claude...")
                pearls_html = engine.extract_pearls(articles, procedure)
                digest_data[procedure] = pearls_html
                successful_cases += 1
                abstract_count += len(articles)
                print(f"    └─ ✓ Complete (abstracts only)")

        except Exception as e:
            logger.error(f"Error processing {procedure}: {e}")
            print(f"    └─ ✗ Error: {e}")
            digest_data[procedure] = f"<p class='no-results'>Error processing literature: {str(e)}</p>"

        print()

    # Create email
    print("📧 Composing email digest...")
    today = datetime.now().strftime("%B %d, %Y")
    subject = f"Surgical Scout Digest - {today}"
    body_html = create_html_email(digest_data)

    # Send email
    print("📤 Sending email...")
    try:
        success = email_sender.send_digest(subject, body_html)

        if success:
            print("\n" + "=" * 60)
            print("✅ SUCCESS!")
            print("=" * 60)
            print(f"Digest sent to: {os.getenv('RECIPIENT_EMAIL')}")
            print(f"Procedures processed: {len(cases)}")
            print(f"Full-text articles analyzed: {full_text_count}")
            if full_text_count > 0:
                for source, count in source_stats.items():
                    if count > 0:
                        print(f"  - From {source}: {count}")
            print(f"Abstract-only articles: {abstract_count}")
            total_articles = full_text_count + abstract_count
            if total_articles > 0:
                full_text_pct = (full_text_count / total_articles) * 100
                print(f"Full-text coverage: {full_text_pct:.1f}%")
            print(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            print("=" * 60)
        else:
            print("\n❌ ERROR: Failed to send email")
            print("Check the logs for details.")
            sys.exit(1)

    except Exception as e:
        logger.error(f"Error sending email: {e}")
        print(f"\n❌ ERROR: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
